# Sample how Q8 can also be done using Pretrained word embeddings i.e GLOVE embeddings

In [1]:
import os
import tweepy 
from textblob import TextBlob

In [89]:
import pandas as pd
import numpy as np
tweet_df1=pd.read_excel('Assignment for ML engineer.xlsx', sheet_name=3)
a=list(tweet_df1['Comment'])
tweet_details = [TextBlob(tweet).sentiment.polarity for tweet in a]

In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv('trainingdata.csv', sep=",", encoding="ISO-8859-1", header=0)

In [27]:
df.columns=['sentiment','a','b','c','d','tweets']
tweet_df = df[796000:804000][['tweets','sentiment']]

In [28]:
tweet_df.head(20)

tweets  sentiment
796000  Sophie is the bombshizzznizle. What am I gunnn...          0
796001  In Class til 1pm yay for me...  damn all I wan...          0
796002                      @arlasalcedo I don`t know.  )          0
796003  waah I wanna watch Unbroke: What You Need To K...          0
796004  i hope the plumber isn't gonna cost a ton of $...          0
796005  @12serendipity21 Oh lucky u...raining cats and...          0
796006                              Its storm'n ova here           0
796007  At DFW airport. I wonder which DGs will be on ...          0
796008  Packing up a day bag. I'm driving to Toledo to...          0
796009  @peterfacinelli Not sure if my entry went thro...          0
796010                         i want twitter on my fone           0
796011                                       is too hot!           0
796012                  Work is not working out im tired           0
796013  @edward_moolaw fine, i guess  i started packin...          0
796014  damn computer acting up.....and i have so much...          0
796015  @ros1e sounds good! I'll think of you while I'...          0
796016  omg ive broken my mouse   ily half-heartedly xxxx          0
796017  I feel sick. I hope I'm not infected with the ...          0
796018  @mooosh If I were shorter I would pretend to b...          0
796019  @adaline_langton Not going either? I thought I...          0

In [29]:
tweet_df['sentiment'] = tweet_df['sentiment'].apply(lambda x: 1 if x==4 else 0)

In [30]:
tweet_df['sentiment'].value_counts()

1    4001
0    3999
Name: sentiment, dtype: int64

In [31]:
tweet_df.head(20)

tweets  sentiment
796000  Sophie is the bombshizzznizle. What am I gunnn...          0
796001  In Class til 1pm yay for me...  damn all I wan...          0
796002                      @arlasalcedo I don`t know.  )          0
796003  waah I wanna watch Unbroke: What You Need To K...          0
796004  i hope the plumber isn't gonna cost a ton of $...          0
796005  @12serendipity21 Oh lucky u...raining cats and...          0
796006                              Its storm'n ova here           0
796007  At DFW airport. I wonder which DGs will be on ...          0
796008  Packing up a day bag. I'm driving to Toledo to...          0
796009  @peterfacinelli Not sure if my entry went thro...          0
796010                         i want twitter on my fone           0
796011                                       is too hot!           0
796012                  Work is not working out im tired           0
796013  @edward_moolaw fine, i guess  i started packin...          0
796014  damn computer acting up.....and i have so much...          0
796015  @ros1e sounds good! I'll think of you while I'...          0
796016  omg ive broken my mouse   ily half-heartedly xxxx          0
796017  I feel sick. I hope I'm not infected with the ...          0
796018  @mooosh If I were shorter I would pretend to b...          0
796019  @adaline_langton Not going either? I thought I...          0

In [32]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding, Activation
from tensorflow.keras.layers import Conv1D , MaxPooling1D, GlobalMaxPooling1D, Dropout
from tensorflow.keras import regularizers
import numpy as np
from numpy import array
from sklearn.model_selection import train_test_split

C:\Users\Surbhi\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Surbhi\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Surbhi\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Surbhi\anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dty

In [33]:
text = tweet_df['tweets'].tolist()
text

["Sophie is the bombshizzznizle. What am I gunnnna go when she's in the jungle of COSTA??? Cry every night? Probably ",
 "In Class til 1pm yay for me...  damn all I wanna do is sleep.. 8 am summer school is not the biz ...It's gonna b a long summer",
 '@arlasalcedo I don`t know.  )',
 "waah I wanna watch Unbroke: What You Need To Know About Money!!! But I can't seem to find it... Garr. ",
 "i hope the plumber isn't gonna cost a ton of $. Ha! I just want my water back ",
 '@12serendipity21 Oh lucky u...raining cats and dogs here ',
 "Its storm'n ova here ",
 "At DFW airport. I wonder which DGs will be on my flight. My parents are here at D terminal - going to Canada. Won't see them. ",
 "Packing up a day bag. I'm driving to Toledo today to see Jordan. I haven't seen her in over a month. Growing up sucks. ",
 '@peterfacinelli Not sure if my entry went through  Site keeps failing.',
 'i want twitter on my fone ',
 'is too hot! ',
 'Work is not working out im tired ',
 "@edward_moolaw fine

In [34]:
y=tweet_df['sentiment']

In [35]:
token = Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\]^_`{"}~\t\n🙏🚨◘📣⚠️🌏🤔✅☣️️⭐',lower=True, split=" ")
token.fit_on_texts(text)

In [36]:
token

In [37]:
vocab_size = len(token.word_index)+1
vocab_size

15547

In [38]:
token.index_word

{1: 'i',
 2: 'to',
 3: 'the',
 4: 'a',
 5: 'my',
 6: 'and',
 7: 'you',
 8: 'is',
 9: 'in',
 10: 'it',
 11: 'for',
 12: 'of',
 13: 'so',
 14: 'on',
 15: 'that',
 16: 'me',
 17: 'just',
 18: 'but',
 19: 'have',
 20: "i'm",
 21: 'at',
 22: 'be',
 23: 'not',
 24: 'with',
 25: 'was',
 26: 'good',
 27: 'farrah',
 28: 'now',
 29: 'this',
 30: 'up',
 31: 'are',
 32: 'day',
 33: 'out',
 34: 'http',
 35: 'quot',
 36: 'no',
 37: 'all',
 38: 'get',
 39: 'like',
 40: 'today',
 41: 'work',
 42: 'go',
 43: 'too',
 44: 'sad',
 45: 'fawcett',
 46: 'your',
 47: 'do',
 48: "it's",
 49: 'about',
 50: 'going',
 51: 'time',
 52: 'what',
 53: 'com',
 54: 'one',
 55: 'will',
 56: 'am',
 57: 'got',
 58: 'love',
 59: 'know',
 60: 'from',
 61: "don't",
 62: 'we',
 63: 'lol',
 64: 'its',
 65: 'if',
 66: 'had',
 67: 'has',
 68: 'u',
 69: 'really',
 70: 'back',
 71: 'her',
 72: 'im',
 73: "can't",
 74: 'can',
 75: 'morning',
 76: 'well',
 77: 'new',
 78: 'more',
 79: 'some',
 80: 'night',
 81: 'how',
 82: 'she',
 8

In [39]:
x=['my health is fine']

In [40]:
token.texts_to_sequences(x)

[[5, 2150, 8, 497]]

In [41]:
encoded_text = token.texts_to_sequences(text)

In [42]:
(encoded_text)

[[1471,
  8,
  3,
  5025,
  52,
  56,
  1,
  5026,
  42,
  88,
  381,
  9,
  3,
  2426,
  12,
  3247,
  800,
  331,
  80,
  510],
 [9,
  444,
  642,
  3248,
  213,
  11,
  16,
  226,
  37,
  1,
  295,
  47,
  8,
  119,
  422,
  56,
  276,
  208,
  8,
  23,
  3,
  1472,
  48,
  171,
  277,
  4,
  149,
  276],
 [5027, 1, 3249, 401, 59],
 [3250,
  1,
  295,
  201,
  5028,
  52,
  7,
  99,
  2,
  59,
  49,
  382,
  18,
  1,
  73,
  643,
  2,
  209,
  10,
  5029],
 [1, 106, 3, 5030, 372, 171, 3251, 4, 2427, 12, 561, 1, 17, 92, 5, 801, 70],
 [5031, 85, 527, 68, 618, 1987, 6, 1083, 96],
 [64, 5032, 5033, 96],
 [21,
  5034,
  1311,
  1,
  539,
  383,
  5035,
  55,
  22,
  14,
  5,
  845,
  5,
  753,
  31,
  96,
  21,
  361,
  5036,
  50,
  2,
  1312,
  332,
  83,
  148],
 [802,
  30,
  4,
  32,
  1084,
  20,
  670,
  2,
  5037,
  40,
  2,
  83,
  1187,
  1,
  458,
  423,
  71,
  9,
  181,
  4,
  619,
  1473,
  30,
  300],
 [696, 23, 182, 65, 5, 1683, 362, 392, 471, 939, 2428],
 [1, 92, 89, 14,

In [43]:
max_length = 120
X = pad_sequences(encoded_text, maxlen=max_length, padding='post')

In [44]:
print(X)

[[ 1471     8     3 ...     0     0     0]
 [    9   444   642 ...     0     0     0]
 [ 5027     1  3249 ...     0     0     0]
 ...
 [ 1227   171    22 ...     0     0     0]
 [15540  1800    17 ...     0     0     0]
 [    5   579  1062 ...     0     0     0]]


In [45]:
X.shape

(8000, 120)

In [46]:
X = np.array(X)
y = np.array(y)

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=42,test_size=0.2, stratify=y)

In [48]:
vec_size = 300

model = Sequential()
model.add(Embedding(vocab_size, vec_size, input_length = max_length))

model.add(Conv1D(64, 8, activation='relu'))
model.add(MaxPooling1D(2))
model.add(Dropout(0.2))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))


model.add(Dense(16, activation='relu'))

model.add(GlobalMaxPooling1D())

model.add(Dense(1,activation='sigmoid'))

In [49]:
model.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])

In [50]:
%%time
model.fit(X_train, y_train, epochs = 5, validation_data= (X_test, y_test))

Train on 6400 samples, validate on 1600 samples
Epoch 1/5
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
6400/6400 [==============================] - 58s 9ms/sample - loss: 0.6926 - accuracy: 0.5083 - val_loss: 0.6320 - val_accuracy: 0.6744
Epoch 2/5
6400/6400 [==============================] - 55s 9ms/sample - loss: 0.5244 - accuracy: 0.7375 - val_loss: 0.4636 - val_accuracy: 0.7625
Epoch 3/5
6400/6400 [==============================] - 58s 9ms/sample - loss: 0.2646 - accuracy: 0.8959 - val_loss: 0.4889 - val_accuracy: 0.7663
Epoch 4/5
6400/6400 [==============================] - 54s 8ms/sample - loss: 0.1116 - accuracy: 0.9614 - val_loss: 0.5900 - val_accuracy: 0.7581
Epoch 5/5
6400/6400 [==============================] - 55s 9ms/sample - loss: 0.0511 - accuracy: 0.9834 - val_loss: 0.7543 - val_accuracy: 0.7500
Wall time: 4min 40s


In [51]:
def get_encoded(x):
    x= token.texts_to_sequences(x)
    x=pad_sequences(x, maxlen=max_length, padding = 'post')
    return x

In [52]:
x = ['worst services. will not come again']

In [53]:
model.predict_classes(get_encoded(x))

array([[0]])

In [54]:
x = ['nice place ']

In [55]:
model.predict_classes(get_encoded(x))

array([[1]])

In [56]:
x = ['worst place ever wont come here ']

In [57]:
model.predict_classes(get_encoded(x))

array([[0]])

In [58]:
x = ['loving this lockdown . i have done so many courses and learned a lot']

In [59]:
model.predict_classes(get_encoded(x))

array([[0]])

In [72]:
x = ['checking out. I was never body shamed but i am a victim of colorism']

In [73]:
model.predict_classes(get_encoded(x))

array([[0]])

In [62]:
x = ['i will never say lies again']

In [63]:
model.predict_classes(get_encoded(x))

array([[1]])

In [64]:
x = ['corona is fake']

In [65]:
model.predict_classes(get_encoded(x))

array([[0]])

In [74]:
from pathlib import Path
emb_dict = {}
glove = open(r'D:\7th SEMESTER\NTCC\glove.twitter.27B.50d.txt', encoding="utf8")
for line in glove:
    values = line.split()
    word = values[0]
    vector = np.asarray(values[1:], dtype='float32')
    emb_dict[word] = vector
glove.close()

In [76]:
print('Loaded %s word vectors.' % len(emb_dict))

Loaded 1193514 word vectors.


In [77]:
emb_matrix = np.zeros((vocab_size, 50))

for w, i in token.word_index.items():
    # The word_index contains a token for all words of the training data so we need to limit that
    if i < vocab_size:
        vect = emb_dict.get(w)
        # Check if the word from the training data occurs in the GloVe word embeddings
        # Otherwise the vector is kept with only zeros
        if vect is not None:
            emb_matrix[i] = vect
    else:
        break

In [78]:
glove_model = Sequential()
glove_model.add(Embedding(vocab_size,50, input_length=max_length))
glove_model.add(Flatten())
glove_model.add(Dense(1, activation='sigmoid'))
glove_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 120, 50)           777350    
_________________________________________________________________
flatten (Flatten)            (None, 6000)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 6001      
Total params: 783,351
Trainable params: 783,351
Non-trainable params: 0
_________________________________________________________________


In [79]:
glove_model.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])

In [80]:
%%time
glove_model.fit(X_train, y_train, epochs = 5, validation_data= (X_test, y_test))

Train on 6400 samples, validate on 1600 samples
Epoch 1/5
6400/6400 [==============================] - 9s 1ms/sample - loss: 0.6669 - accuracy: 0.6067 - val_loss: 0.5906 - val_accuracy: 0.7262
Epoch 2/5
6400/6400 [==============================] - 7s 1ms/sample - loss: 0.4600 - accuracy: 0.8189 - val_loss: 0.4687 - val_accuracy: 0.7694
Epoch 3/5
6400/6400 [==============================] - 7s 1ms/sample - loss: 0.2665 - accuracy: 0.9184 - val_loss: 0.4377 - val_accuracy: 0.7944
Epoch 4/5
6400/6400 [==============================] - 7s 1ms/sample - loss: 0.1430 - accuracy: 0.9708 - val_loss: 0.4325 - val_accuracy: 0.7844
Epoch 5/5
6400/6400 [==============================] - 7s 1ms/sample - loss: 0.0792 - accuracy: 0.9878 - val_loss: 0.4346 - val_accuracy: 0.7800
Wall time: 37.2 s


In [81]:
x = ['worst services. will not come again']
model.predict_classes(get_encoded(x))

array([[0]])

In [82]:
x = ['worst services. will not come again']
glove_model.predict_classes(get_encoded(x))

array([[0]])

In [83]:
x = ['i will never say lies again']
glove_model.predict_classes(get_encoded(x))

array([[1]])

In [84]:
x = ['Instead of dumping thousands of liters of beer that could not be delivered due to #coronavirus closures, a brewery in Germany got creative — and is giving it away for free.']
glove_model.predict_classes(get_encoded(x))

array([[0]])

In [85]:
x = ['How interesting! S Korea actually didn’t do much Testing! Because they started Testing IMMEDIATELY at the Beginning, they caught it & stopped #Corona Early like a Fire. Only 248 deaths!! TRUMP took FOREVER, let the Fire SPREAD without doing anything, & now it burned everything!']
glove_model.predict_classes(get_encoded(x))

array([[0]])

In [86]:
x = ['what the hell is this']
glove_model.predict_classes(get_encoded(x))

array([[0]])

In [88]:
x = ['checking out. I was never body shamed but i am a victim of colorism']
glove_model.predict_classes(get_encoded(x))

array([[0]])

In [93]:
tweet_df1['sentiment']=glove_model.predict_classes(get_encoded(a))
tweet_df1.head(20)

Comment  sentiment
0   OMG i never Belive that i will be able to loss...          0
1   @plumbodylovin great giveaway lol... I was ski...          1
2   I dont believe in body shaming at all\t\t\t\t\...          0
3   Eve i had faced bodyshaming but I don't care n...          0
4   Same i was under wait till my school days and ...          0
5   checking out @plumbodylovin . I was never body...          0
6   I hv been hving this\t\t\t\t\t\t\t\t\t\t\t\t\t...          0
7   You will always find a syrup and cold/cough ta...          0
8   This was too needed in this weather\t\t\t\t\t\...          0
9   I really have to be careful, because getting a...          0
10  That's wat i wanted for my father @cofsils_ind...          0
11  I am drooling over @ovenstory pizza\t\t\t\t\t\...          1
12  Haven't had pizza for so long\t\t\t\t\t\t\t\t\...          1
13  I miss hving cheese burst pizza\t\t\t\t\t\t\t\...          0
14  I need this pizza @ovenstroy\t\t\t\t\t\t\t\t\t...          0
15  Oh wow I'm feeling so hungry\t\t\t\t\t\t\t\t\t...          0
16  Girl this look is bomb af\t\t\t\t\t\t\t\t\t\t\...          1
17   OMG!!!! Me want!!!! Paryushan though....\t\t\...          0
18  Awaiting for the video\t\t\t\t\t\t\t\t\t\t\t\t...          0
19  The word pretty is worthless without you\t\t\t...          1

In [96]:
tweet_df1['sentiment'].value_counts()

1    112
0     39
Name: sentiment, dtype: int64